version: '3.8'
services:
  app:
    container_name: App
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ["sh", "-c", "php artisan serve --host=0.0.0.0 --port=8000"]
    volumes:
      - ./app:/app
      - composer-volume:/app/vendor
      - node-modules-volume:/app/node_modules
    ports:
      - 80:8000
      - 5173:5173
    depends_on:
      - db
      - mailpit
    tty: true
    stdin_open: true

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "laravel"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "toor"
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306

  mailpit:
    image: axllent/mailpit
    container_name: MailPit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-volume:
  composer-volume:
  node-modules-volume:
